version: "3.6"
services:
  api:
    image: web3labs/epirus-free-api:latest
    environment:
      - ENABLE_PRIVATE_QUORUM=enabled
      - NODE_ENDPOINT=http://quorum-testbed_node1_1:8545
      - MONGO_CLIENT_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=epirus
    depends_on:
      - mongodb
    networks:
      - epirus

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    entrypoint: mongod --logpath=/dev/null --bind_ip "0.0.0.0"
    networks:
      - epirus

  web:
    image: web3labs/epirus-free-web:latest
    environment:
      - API_URL=/api
    depends_on:
      - api
    networks:
      - epirus
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./5xx.html:/www/error_pages/5xx.html
    ports:
      - 22222:80
    depends_on:
      - api
      - web
    networks:
      - epirus

networks:
  epirus:
    name: epirus-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24